spring.application.name=medislot-sse-lab
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/medislot_sse_lab}
spring.mvc.async.request-timeout=120000
server.error.include-message=always
spring.profiles.active=lab